### ISSUE TITLE
Modules dynamicly reload settings, which should not reloaded this way

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#466]
Build: Develop-2

Steps to reproduce:
1. Open settings -> Messaging Modules -> Levels.
2. Change Experience growth from static to random.
3. Close settings via OK button.
4. We get warning about restart to apply this setting.
5. Open settings -> Messaging Modules -> Levels.

Expected:
Levels Settings open.

Bug:
On step 5 in console:
```

Traceback (most recent call last):  
  File "src\modules\gui.py", line 306, in on_tree_ctrl_changed  
  File "src\modules\gui.py", line 489, in fill_page_with_content  
  File "src\modules\gui.py", line 518, in create_page  
  File "src\modules\gui.py", line 559, in create_page_items  
  File "src\modules\interface\functions.py", line 81, in create_static_box  
  File "src\modules\interface\functions.py", line 288, in create_dropdown  
ValueError: tuple.index(x): x not in tuple  

```

Levels Settings not open.

**Comment by DeForce** [comment]
Fixed with #461
