### ISSUE TITLE
Can't close chat after deactivate activated module

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#474]
Build: Develop-7

Steps to reproduce:
1. Start chat.
2. Open settings -> Messaging Modules
3. Activate blacklist module.
4. Save settings and close chat.
5. Start chat.
6. Open settings -> Messaging Modules
7. Deactivate blacklist module.
8. Save settings via OK button.
9. Close chat via Close button.

Expected:
Chat closed

Bug:
Chat not closed. Console error:
```
Traceback (most recent call last):
  File "src\modules\gui.py", line 888, in on_close
  File "src\modules\helper\module.py", line 114, in apply_settings
  File "src\modules\helper\parser.py", line 110, in save_settings
  File "site-packages\yaml\__init__.py", line 218, in safe_dump
  File "site-packages\yaml\__init__.py", line 190, in dump_all
  File "site-packages\yaml\representer.py", line 28, in represent
  File "site-packages\yaml\representer.py", line 57, in represent_data
  File "site-packages\yaml\representer.py", line 225, in represent_dict
  File "site-packages\yaml\representer.py", line 123, in represent_mapping
  File "site-packages\yaml\representer.py", line 67, in represent_data
  File "site-packages\yaml\representer.py", line 249, in represent_undefined
yaml.representer.RepresenterError: cannot represent an object: <modules.interfac
e.types.LCGridSingle object at 0x032A4290>
```

**Comment by DeForce** [comment]
fixed
