### ISSUE TITLE
Blacklist module not open in settings after activated

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#475]
Build: Develop-7

Steps to reproduce:
1. Start chat.
2. Open settings -> Messaging Modules.
3. Activate blacklist module.
4. Save settings and close chat.
5. Start chat.
6. Open settings -> Messaging Modules -> Blacklist

Expected:
Blacklist module settings opens.

Bug:
Blacklist module sttings not opens. Console error:
```
Traceback (most recent call last):
  File "src\modules\gui.py", line 306, in on_tree_ctrl_changed
  File "src\modules\gui.py", line 495, in fill_page_with_content
  File "src\modules\gui.py", line 524, in create_page
  File "src\modules\gui.py", line 565, in create_page_items
  File "src\modules\interface\elements.py", line 165, in create_list
  File "src\modules\interface\types.py", line 193, in __iter__
AttributeError: 'NoneType' object has no attribute '__iter__'
```

**Comment by DeForce** [comment]
Should be fixed
